
#pragma once
#define MASTER_TX_BUFFER_SIZE 512
#define SLAVE_TX_BUFFER_SIZE 512
#define MAC_ADDRESS_SIZE 6
#define UPDATE_ADD_CLIENT 0
#define UPDATE_REMOVE_CLIENT 1
#define UPDATE_ADD_SERVER 2
#define UPDATE_REMOVE_SERVER 3